server:
  servlet:
    context-path: /darryring

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///darryring?serverTimezone=UTC
    username: root
    password: 1234

  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 50
        # 最小空闲连接数
        min-idle: 10
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1


mybatis:
  type-aliases-package: com.darryring.pojo
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true



pagehelper:
  helperDialect: mysql
  reasonable: true
  page-size-zero: true


